{
 "title": "Wireguard Overview",
 "description": "Wireguard Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Device Info ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wireguard_device_info",
     "legendFormat": "Device: {{device}} / Public Key {{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wireguard_peer_info" }
   ]
  },
  {
   "title": "Peer Last Handshake",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(wireguard_peer_last_handshake_seconds)",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Transmit Bytes Total (1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(wireguard_peer_transmit_bytes_total[1m]) * on (public_key) group_left(name) wireguard_peer_info * on (instance) group_left(device) wireguard_device_info",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Receive Bytes Total (1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(wireguard_peer_receive_bytes_total[1m]) * on (public_key) group_left(name) wireguard_peer_info * on (instance) group_left(device) wireguard_device_info",
     "legendFormat": "{{public_key}}"
    }
   ]
  }
 ]
}